import React from 'react';
import { motion } from 'framer-motion';
import profilepic from '../assets/images/profilepic.png';

export default function Hero() {
  return (
    <div className="relative overflow-clip min-h-screen text-white bg-[linear-gradient(to_bottom,#000,#071E18_35%,#208A65_67%,#35FB8E_85%)]">
          
      {/* Background Decoration */}
      <div
        className="absolute bg-black w-[2400px] h-[1000px] rounded-[50%] left-1/2 -translate-x-1/2 
                      bg-[radial-gradient(closest-side,#000_85%,#249974)] top-[450px]
                      border-[1px] border-[#8CD6DE]/30"
      />

      {/* Container */}
      <div className="container relative mx-auto px-4 pt-12 pb-24">
        
        {/* Example Content */}
        <div className='flex flex-col items-center justify-center z-10'>
        <motion.div
          
          initial={{ opacity: 0, scale: 0.5}}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8 }}
          className='relative mb-8 mt-24'
        >
            <div className='absolute inset-0 bg-gradient-to-b from-emerald-500/20 to-transparent rounded-full blur-3xl'></div>
            <img
             src={profilepic} 
             alt="Mike"
             className='W-[250PX] relative z-10' />
        </motion.div>
        </div>

        <h1 className="text-4xl font-bold text-center mt-8">Welcome to My Portfolio</h1>
        <p className="text-center mt-4 text-lg">
          I am a passionate developer, eager to create impactful applications.
        </p>
      </div>
    </div>
  );
}
